import { Candidat } from './candidat';

export const CANDIDATS: Candidat [] = [
    {
      "_id": "930c92da2319965dfe3882b9",
      "createdAt": "2118-08-25T17:01:06.575Z",
      "updatedAt": "2050-12-10T04:16:44.814Z",
      "province": "Ronjo cuwud.",
      "jobTitle": "Todbeke luahuafi.",
      "postalCode": "Buugaevu am.",
      "email": "Ohefevi uva.",
      "city": "Got kuspitdif.",
      "name": "Pikbu ucepoeh.",
      "description": "Adeerfag fiwek.",
      "address": "Ifubo zuknac.",
      "published": false,
      "phone": "Tabuheg baw."
    },
    {
      "_id": "379b76ae6d194bb686f26f65",
      "createdAt": "2099-08-29T19:07:20.211Z",
      "updatedAt": "2080-12-21T08:46:36.527Z",
      "province": "Ijene vallaju.",
      "jobTitle": "Uskew nuncag.",
      "postalCode": "Tesubed kemzal.",
      "email": "Oli nakko.",
      "city": "Ewekel jipa.",
      "name": "Ilo hijot.",
      "description": "Wawfulav avagbek.",
      "address": "Zazoska sevevka.",
      "published": false,
      "phone": "Pefkocap tucabuh."
    },
    {
        "_id": "930c92da2319965dfe3882b9",
        "createdAt": "2118-08-25T17:01:06.575Z",
        "updatedAt": "2050-12-10T04:16:44.814Z",
        "province": "Ronjo cuwud.",
        "jobTitle": "Todbeke luahuafi.",
        "postalCode": "Buugaevu am.",
        "email": "Ohefevi uva.",
        "city": "Got kuspitdif.",
        "name": "Pikbu ucepoeh.",
        "description": "Adeerfag fiwek.",
        "address": "Ifubo zuknac.",
        "published": false,
        "phone": "Tabuheg baw."
      },
      {
        "_id": "379b76ae6d194bb686f26f65",
        "createdAt": "2099-08-29T19:07:20.211Z",
        "updatedAt": "2080-12-21T08:46:36.527Z",
        "province": "Ijene vallaju.",
        "jobTitle": "Uskew nuncag.",
        "postalCode": "Tesubed kemzal.",
        "email": "Oli nakko.",
        "city": "Ewekel jipa.",
        "name": "Ilo hijot.",
        "description": "Wawfulav avagbek.",
        "address": "Zazoska sevevka.",
        "published": false,
        "phone": "Pefkocap tucabuh."
      },
      {
        "_id": "930c92da2319965dfe3882b9",
        "createdAt": "2118-08-25T17:01:06.575Z",
        "updatedAt": "2050-12-10T04:16:44.814Z",
        "province": "Ronjo cuwud.",
        "jobTitle": "Todbeke luahuafi.",
        "postalCode": "Buugaevu am.",
        "email": "Ohefevi uva.",
        "city": "Got kuspitdif.",
        "name": "Pikbu ucepoeh.",
        "description": "Adeerfag fiwek.",
        "address": "Ifubo zuknac.",
        "published": false,
        "phone": "Tabuheg baw."
      },
      {
        "_id": "379b76ae6d194bb686f26f65",
        "createdAt": "2099-08-29T19:07:20.211Z",
        "updatedAt": "2080-12-21T08:46:36.527Z",
        "province": "Ijene vallaju.",
        "jobTitle": "Uskew nuncag.",
        "postalCode": "Tesubed kemzal.",
        "email": "Oli nakko.",
        "city": "Ewekel jipa.",
        "name": "Ilo hijot.",
        "description": "Wawfulav avagbek.",
        "address": "Zazoska sevevka.",
        "published": false,
        "phone": "Pefkocap tucabuh."
      },
      {
        "_id": "930c92da2319965dfe3882b9",
        "createdAt": "2118-08-25T17:01:06.575Z",
        "updatedAt": "2050-12-10T04:16:44.814Z",
        "province": "Ronjo cuwud.",
        "jobTitle": "Todbeke luahuafi.",
        "postalCode": "Buugaevu am.",
        "email": "Ohefevi uva.",
        "city": "Got kuspitdif.",
        "name": "Pikbu ucepoeh.",
        "description": "Adeerfag fiwek.",
        "address": "Ifubo zuknac.",
        "published": false,
        "phone": "Tabuheg baw."
      },
      {
        "_id": "379b76ae6d194bb686f26f65",
        "createdAt": "2099-08-29T19:07:20.211Z",
        "updatedAt": "2080-12-21T08:46:36.527Z",
        "province": "Ijene vallaju.",
        "jobTitle": "Uskew nuncag.",
        "postalCode": "Tesubed kemzal.",
        "email": "Oli nakko.",
        "city": "Ewekel jipa.",
        "name": "Ilo hijot.",
        "description": "Wawfulav avagbek.",
        "address": "Zazoska sevevka.",
        "published": false,
        "phone": "Pefkocap tucabuh."
      },
      {
        "_id": "930c92da2319965dfe3882b9",
        "createdAt": "2118-08-25T17:01:06.575Z",
        "updatedAt": "2050-12-10T04:16:44.814Z",
        "province": "Ronjo cuwud.",
        "jobTitle": "Todbeke luahuafi.",
        "postalCode": "Buugaevu am.",
        "email": "Ohefevi uva.",
        "city": "Got kuspitdif.",
        "name": "Pikbu ucepoeh.",
        "description": "Adeerfag fiwek.",
        "address": "Ifubo zuknac.",
        "published": false,
        "phone": "Tabuheg baw."
      },
      {
        "_id": "379b76ae6d194bb686f26f65",
        "createdAt": "2099-08-29T19:07:20.211Z",
        "updatedAt": "2080-12-21T08:46:36.527Z",
        "province": "Ijene vallaju.",
        "jobTitle": "Uskew nuncag.",
        "postalCode": "Tesubed kemzal.",
        "email": "Oli nakko.",
        "city": "Ewekel jipa.",
        "name": "Ilo hijot.",
        "description": "Wawfulav avagbek.",
        "address": "Zazoska sevevka.",
        "published": false,
        "phone": "Pefkocap tucabuh."
      },
      {
        "_id": "930c92da2319965dfe3882b9",
        "createdAt": "2118-08-25T17:01:06.575Z",
        "updatedAt": "2050-12-10T04:16:44.814Z",
        "province": "Ronjo cuwud.",
        "jobTitle": "Todbeke luahuafi.",
        "postalCode": "Buugaevu am.",
        "email": "Ohefevi uva.",
        "city": "Got kuspitdif.",
        "name": "Pikbu ucepoeh.",
        "description": "Adeerfag fiwek.",
        "address": "Ifubo zuknac.",
        "published": false,
        "phone": "Tabuheg baw."
      },
      {
        "_id": "379b76ae6d194bb686f26f65",
        "createdAt": "2099-08-29T19:07:20.211Z",
        "updatedAt": "2080-12-21T08:46:36.527Z",
        "province": "Ijene vallaju.",
        "jobTitle": "Uskew nuncag.",
        "postalCode": "Tesubed kemzal.",
        "email": "Oli nakko.",
        "city": "Ewekel jipa.",
        "name": "Ilo hijot.",
        "description": "Wawfulav avagbek.",
        "address": "Zazoska sevevka.",
        "published": false,
        "phone": "Pefkocap tucabuh."
      }
  ]